name: PlayTracker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Instalar Dependencias
      run: npm install

    - name: Ejecutar Pruebas Unitarias (Jest >= 80% Coverage)
      run: npm test

    - name: Simulación de Despliegue
      run: echo "Pruebas exitosas. Listo para desplegar en Producción."